In [1]:
from sklearn.datasets import load_boston

In [2]:
import pandas as pd
import numpy as np

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
 df = load_boston()

In [5]:
X = df.data

In [6]:
X

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [7]:
df.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [8]:
y = df.target

In [9]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)

In [12]:
from sklearn.ensemble import AdaBoostRegressor

In [13]:
ada = AdaBoostRegressor(base_estimator=None,
                        n_estimators=20,
                        learning_rate=0.7,
                        loss='linear')

In [14]:
ada.fit(X_train, y_train)

AdaBoostRegressor(learning_rate=0.7, n_estimators=20)

In [15]:
y_pred = ada.predict(X_test)

In [16]:
y_pred

array([25.02771084, 26.98      , 17.27682927, 25.46870229, 17.07238494,
       21.34460432, 19.378     , 15.98534483, 20.49459459, 20.42881356,
       19.378     , 19.378     , 12.26590909, 21.34460432, 20.42881356,
       21.34460432, 19.378     , 12.29620253, 43.825     , 16.68214286,
       25.46870229, 25.46870229, 17.07238494, 25.15333333, 16.26818182,
       18.275     , 22.88549223, 15.98534483, 19.378     , 20.42881356,
       20.19411765, 25.46870229, 20.72857143, 19.78395062, 17.07238494,
       17.07238494, 36.321875  , 21.83947368, 19.78395062, 25.15333333,
       17.22488038, 27.84      , 43.825     , 20.42881356, 25.02771084,
       16.26818182, 18.67276596, 25.46870229, 19.378     , 26.41719745,
       20.49459459, 29.77102804, 19.378     , 26.00416667, 45.00606061,
       20.49459459, 16.68214286, 28.55322581, 25.15333333, 19.12190476,
       25.46870229, 34.27333333, 26.98      , 20.42881356, 26.52280702,
       17.22488038, 16.68214286, 25.46870229, 26.98      , 16.26

In [17]:
from sklearn.metrics import mean_squared_error

In [18]:
mse = mean_squared_error(y_test, y_pred)

In [19]:
mse

13.616296507911352

## Different Estimator

In [20]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import AdaBoostRegressor

In [21]:
lr = LinearRegression()
ada = AdaBoostRegressor(base_estimator=lr,
                        n_estimators=20,
                        learning_rate=0.7,
                        loss='linear')

In [22]:
ada.fit(X_train, y_train)

AdaBoostRegressor(base_estimator=LinearRegression(), learning_rate=0.7,
                  n_estimators=20)

In [23]:
y_pred = ada.predict(X_test)

In [24]:
y_pred

array([30.70006198, 39.73283421, 14.39713398, 27.19124134, 20.01496595,
       23.88297324, 17.42850862, 12.82467591, 28.47225844, 21.51001704,
       26.79166591, 18.11071447, -6.60767231, 22.30111047, 20.81580964,
       28.20494366, 20.40891593,  6.70664344, 40.56584713, 19.11551318,
       28.13337623, 30.79558151, 10.07265926, 23.51243985, 20.82923921,
       20.58273517, 25.27224683, 13.96166976, 24.87600195, 20.37940665,
       24.25342938, 26.47903802, 25.39801981, 23.29300306, 18.89895324,
       16.6827961 , 31.66279958, 20.6597787 , 25.08730544, 25.24680055,
       14.58923649, 34.07540492, 42.37212702, 18.50360536, 28.59508498,
       20.8542886 , 14.26629274, 26.23934552, 23.75631816, 30.76104775,
       22.3330788 , 34.90403323, 15.27813602, 26.01887235, 39.9094873 ,
       26.35133519, 20.77544326, 33.04919941, 25.43741635, 13.08624843,
       21.98199824, 29.78285193, 33.85474588, 17.12475186, 19.8655316 ,
       18.95692118, 22.03209812, 27.6881244 , 31.26723986, 12.30

In [25]:
mse = mean_squared_error(y_test, y_pred)

In [26]:
print(mse)

25.82370597105754


In [27]:
from sklearn.svm import SVR

In [28]:
svr=SVR()

In [29]:
ada = AdaBoostRegressor(base_estimator=svr,
                        n_estimators=20,
                        learning_rate=0.7,
                        loss='linear')

In [30]:
ada.fit(X_train, y_train)

AdaBoostRegressor(base_estimator=SVR(), learning_rate=0.7, n_estimators=20)

In [31]:
y_pred = ada.predict(X_test)

In [32]:
y_pred

array([23.00631808, 25.19265988, 16.93488184, 23.91433713, 17.31269415,
       21.05609357, 22.67886723, 20.09710716, 17.46970452, 21.28337259,
       23.16700305, 22.62996546, 13.75267697, 21.58620386, 23.26634425,
       17.6218173 , 24.55961729, 16.91341128, 25.63554661, 17.29585297,
       25.6730416 , 25.17143188, 22.05383773, 23.64453409, 16.59221871,
       16.9120801 , 22.03347257, 13.46043641, 23.15293675, 21.4613546 ,
       22.89552783, 23.7067483 , 17.2990946 , 17.27441172, 16.69112388,
       19.02660356, 24.46332418, 24.98712288, 23.5730921 , 23.77505965,
       21.34609275, 25.1367403 , 26.26471418, 22.93603186, 23.80544229,
       17.31714451, 22.06308796, 23.84699542, 17.55170755, 23.60208808,
       22.82166415, 25.52397063, 22.53526015, 21.60266481, 24.43333937,
       18.00702321, 17.29663168, 25.8604532 , 24.55659377, 22.59317027,
       24.20758262, 26.3420106 , 23.61203661, 22.12047377, 22.3921262 ,
       23.0055451 , 17.25973207, 24.46818143, 25.75502824, 13.55

In [33]:
mse = mean_squared_error(y_test, y_pred)

In [34]:
mse

50.545537808821024

# Conclusion

- MSE of AdaBoost is 13.285184745258613.
- MSE of Linear Regression is 24.434137371116528.
- MSE of Support Vector Regressor is 52.16083097903864.
- Choosig AdaBoost algorithm for this dataset, because the smaller the mean squared error, the closer to finding the line of best fit.


# Choosing optimal Hyperparameters for tree

# Grid Search

In [35]:
from sklearn.model_selection import GridSearchCV

In [36]:
# dictionary of hyperparameters as key value to be tried

dict = {
    'n_estimators' : [10000,50,100,500],
    'learning_rate' : [0.001,0.01,0.1,1.0]
   
}

In [37]:
dict

{'n_estimators': [10000, 50, 100, 500],
 'learning_rate': [0.001, 0.01, 0.1, 1.0]}

In [38]:
# Instance of AdaBoost
ada = AdaBoostRegressor()

In [39]:
# Instance of GridSearchCV
GS = GridSearchCV(estimator=ada, param_grid=dict, cv=4, n_jobs=-1, verbose=1, scoring='accuracy')


In [40]:
GS.fit(X_train,y_train)

Fitting 4 folds for each of 16 candidates, totalling 64 fits


GridSearchCV(cv=4, estimator=AdaBoostRegressor(), n_jobs=-1,
             param_grid={'learning_rate': [0.001, 0.01, 0.1, 1.0],
                         'n_estimators': [10000, 50, 100, 500]},
             scoring='accuracy', verbose=1)

In [41]:
# best Estimator og GridSearch
GS.best_estimator_

AdaBoostRegressor(learning_rate=0.001, n_estimators=10000)

In [42]:
# Best Estimator of Decision Tree
DTC_best = GS.best_estimator_

In [43]:
GS.best_params_

{'learning_rate': 0.001, 'n_estimators': 10000}

# Random SearchCV