In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [21]:
from sklearn.datasets import load_iris

In [22]:
df = load_iris()

In [23]:
df.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [24]:
df.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [25]:
df.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [26]:
df.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import SVC, SVR
from sklearn import datasets

In [28]:
y = df.target
X= df.data

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size = 0.80, test_size = 0.20, random_state = 10)

In [31]:
X_train

array([[6.6, 2.9, 4.6, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [7.2, 3. , 5.8, 1.6],
       [5.8, 2.8, 5.1, 2.4],
       [6.3, 2.5, 5. , 1.9],
       [4.6, 3.2, 1.4, 0.2],
       [6.7, 3.3, 5.7, 2.1],
       [6.9, 3.2, 5.7, 2.3],
       [7.7, 2.6, 6.9, 2.3],
       [6.9, 3.1, 5.1, 2.3],
       [5. , 3.4, 1.6, 0.4],
       [5. , 3.5, 1.6, 0.6],
       [5.2, 2.7, 3.9, 1.4],
       [4.5, 2.3, 1.3, 0.3],
       [6.3, 3.3, 4.7, 1.6],
       [5.2, 4.1, 1.5, 0.1],
       [6.9, 3.1, 4.9, 1.5],
       [5.9, 3.2, 4.8, 1.8],
       [5.6, 2.8, 4.9, 2. ],
       [6.7, 3.3, 5.7, 2.5],
       [6.2, 2.2, 4.5, 1.5],
       [7.2, 3.6, 6.1, 2.5],
       [5.5, 2.4, 3.7, 1. ],
       [6. , 2.9, 4.5, 1.5],
       [6.4, 3.2, 4.5, 1.5],
       [5.8, 4. , 1.2, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [6.1, 2.9, 4.7, 1.4],
       [5.4, 3.4, 1.7, 0.2],
       [6.4, 3.1, 5.5, 1.8],
       [4.7, 3.2, 1.6, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [4.9, 2.5, 4.5, 1.7],
       [5.1, 2.5, 3. , 1.1],
       [6.7, 3

# simple SVC

In [32]:
svc=SVC()

In [70]:
svc.fit(X_train,y_train)

SVC(degree=4, kernel='poly')

In [79]:
y_pred = svc.predict(X_test)

In [80]:
y_pred

array([1, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2])

In [81]:
y_test

array([1, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2])

## Accuracy

In [82]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [90]:
accuracy = accuracy_score(y_test, y_pred)

In [91]:
accuracy

1.0

## Confusion Matrix

In [85]:
cm = confusion_matrix(y_test, y_pred)

In [86]:
cm

array([[10,  0,  0],
       [ 0, 13,  0],
       [ 0,  0,  7]], dtype=int64)

In [87]:
TN = cm[0][0]
TP = cm[1][1]
FN = cm[1][0]
FP = cm[0][1]

In [88]:
accuracy = (TN+TP)/(TN+TP+FN+FP)

In [89]:
accuracy

1.0

# SVM TO SVC

## Linear Kernel

In [48]:
C = 1.0

In [49]:
svc = SVC(kernel='linear', random_state = 0)

In [50]:
svc.fit(X,y)

SVC(kernel='linear', random_state=0)

In [51]:
y_pred = svc.predict(X_test)

In [52]:
y_pred

array([1, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2])

In [53]:
from sklearn import metrics

In [54]:
print(metrics.accuracy_score(y_test, y_pred))

1.0


## RBF Kernel

In [55]:
from sklearn.svm import SVC

In [56]:
svc = SVC(kernel = 'rbf')

In [57]:
svc.fit(X_train, y_train)

SVC()

In [58]:
y_pred = svc.predict(X_test)

In [59]:
print(metrics.accuracy_score(y_test, y_pred))

0.9666666666666667


## Polynomial Kernel

In [60]:
svc = SVC(kernel = 'poly' , degree = 4)

In [61]:
svc.fit(X_train, y_train)

SVC(degree=4, kernel='poly')

In [62]:
y_pred = svc.predict(X_test)

In [63]:
print(metrics.accuracy_score(y_test, y_pred))

1.0


## Conclusion

- Linear kernel accuracy is 100%
- RBF kernel accuracy is 96%
- That's why linear is more accurate.